- name: loops demo
  hosts: localhost
  become: yes
  tasks:
   - name: install pakages
     ansible.builtin.dnf:
      name: "{{item}}"
      enabled: yes
      state: started

     loop:
     - nginx
     - git 
     - postfix