- name: display information
  hosts: localhost
  vars_files:
   - vars-files.yaml
  tasks:
    - name: print info
      ansible.builtin.debug: 
       msg: "hi {{course}} , duration {{duration}} , trainer {{trainer}}"


